CREATE TABLE LOTE(
ID_LOTE INT NOT NULL PRIMARY KEY
);

CREATE TABLE PRODUTO(
ID_PRODUTO INT NOT NULL PRIMARY KEY,
DESCRICAO_SIMPLES VARCHAR(10) NOT NULL,
DESCRICAO_COMPLETA VARCHAR(40),
CATEGORIA VARCHAR(10) NOT NULL);

CREATE TABLE LOTEXPRODUTO(
ID_LOTEXPROD INT NOT NULL PRIMARY KEY,
ID_LOTE INT NOT NULL,ID_PRODUTO INT NOT NULL,
CONSTRAINT FK_LOTE FOREIGN KEY (ID_LOTE) REFERENCES LOTE(ID_LOTE),
CONSTRAINT FK_PROD FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO));

CREATE TABLE LEILAO(ID_LEILAO INT NOT NULL PRIMARY KEY,
ATIVO INT NOT NULL CHECK(ATIVO IN(1,0)),
VALOR_INICIAl_LOTE INT NOT NULL,
TIPO VARCHAR(10) NOT NULL CHECK(TIPO IN('DEMANDA', 'OFERTA')),
ID_VENDEDOR_COMPRADOR INT NOT NULL,ID_LOTE INT NOT NULL,
DATA_INICIO DATE NOT NULL,DATE_FIM DATE NOT NULL,
CONSTRAINT FK_ID_LOTE FOREIGN KEY(ID_LOTE) REFERENCES LOTE(ID_LOTE));

CREATE TABLE USUARIO(
CPF_CNPJ INT NOT NULL PRIMARY KEY,NOME VARCHAR(20) NOT NULL,
EMAIL VARCHAR(30) NOT NULL);

CREATE TABLE LANCE(ID_LANCE INT NOT NULL PRIMARY KEY,
CPF_CNPJ INT NOT NULL,ID_LEILAO INT NOT NULL,
CONSTRAINT FK_IDUSER FOREIGN KEY (CPF_CNPJ) REFERENCES USUARIO(CPF_CNPJ),
CONSTRAINT FK_ID_LEILAO FOREIGN KEY (ID_LEILAO) REFERENCES LEILAO(ID_LEILAO));